plugins:
  - jest
env:
  node: true
  jest: true
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2020
rules:
  no-console: 0
  import/extensions: 0